### ISSUE TITLE
Compilation error, org.kohsuke:asm3:3.3.0 dependency is missing from pom file,

### ISSUE THREAD

**Issue by tzachs** [jenkinsci/lib-file-leak-detector#27]
Hi,

I've cloned the project (zip file) and ran mvn clean package.
I got compilation error due to class not file belonging to org.kohsuke.asm3.

Adding the following helped.

<dependency>
    <groupId>org.kohsuke</groupId>
    <artifactId>asm3</artifactId>
    <version>3.3.0</version>
</dependency>

**Comment by centic9** [comment]
I think I solved this for me by changing from asm3 to asm5 in the code, see https://github.com/centic9/file-leak-detector/commit/8e73796da828f35b6613ef296058d0cfe3180de6

**Comment by tzachs** [comment]
Thanks centic. I was able to solve buy adding the dependency also.

**Comment by basil** [comment]
This is no longer an issue in recent builds.
